# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koctl < Formula
  desc "Opinionated Kong Konnect organization orchestration via declarative configuration"
  homepage "https://github.com/Kong/konnect-orchestrator"
  version "0.15.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.15.0/konnect-orchestrator_darwin_amd64.zip"
      sha256 "6c2bca09d5d942c6e227a159e3e9e10b18a0479ec11c13306cce50bdfacb7ef4"

      def install
        bin.install "koctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.15.0/konnect-orchestrator_darwin_arm64.zip"
      sha256 "dc239c4ddfbb3e4b893fcb78ef55688f86fd53b6d3d833f03e45119201516156"

      def install
        bin.install "koctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.15.0/konnect-orchestrator_linux_amd64.zip"
        sha256 "d38c7d247731d664808cd6848a4094595c86d6468e6940195d785cbe9c6f80bf"

        def install
          bin.install "koctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.15.0/konnect-orchestrator_linux_arm64.zip"
        sha256 "6269c6d533d6ba14ff7761506000128d1cbad88020ca95c6343d0d426a9fa0c4"

        def install
          bin.install "koctl"
        end
      end
    end
  end

  test do
    system "#{bin}/koctl", "version"
  end
end
