# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koctl < Formula
  desc "Opinionated Kong Konnect organization orchestration via declarative configuration"
  homepage "https://github.com/Kong/konnect-orchestrator"
  version "0.14.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.14.0/konnect-orchestrator_darwin_amd64.zip"
      sha256 "7b0aaa6571e2f749b3e016dbdc1cdb395fbf9b58a2ed816b0c573a65ac5d0e8e"

      def install
        bin.install "koctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.14.0/konnect-orchestrator_darwin_arm64.zip"
      sha256 "155c7b1bf2310f21d90d0a7a7d0e27e0f5c2edef446d087ea55b18c4b8f27e7e"

      def install
        bin.install "koctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.14.0/konnect-orchestrator_linux_amd64.zip"
        sha256 "1063d551725ae0f288577d82d99d38d90cf593ad912a3760fafef7b2e5f8c720"

        def install
          bin.install "koctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.14.0/konnect-orchestrator_linux_arm64.zip"
        sha256 "73f0fe534db9360a2e85653e3f4e813f4656c73d2dc2ba9928b8c38cac420162"

        def install
          bin.install "koctl"
        end
      end
    end
  end

  test do
    system "#{bin}/koctl", "version"
  end
end
