# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Koctl < Formula
  desc "Opinionated Kong Konnect organization orchestration via declarative configuration"
  homepage "https://github.com/Kong/konnect-orchestrator"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.6.0/konnect-orchestrator_darwin_amd64.zip"
      sha256 "bfb52223713f74d4eaa4c3ec10c411184934939a9c04142305da1a683cac0adf"

      def install
        bin.install "koctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.6.0/konnect-orchestrator_darwin_arm64.zip"
      sha256 "6a702980739c59ba4aa664e0c239b662e1db8cec210e70743541e480cc841347"

      def install
        bin.install "koctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.6.0/konnect-orchestrator_linux_amd64.zip"
        sha256 "a147489045095f47b7044c28dc172f4ef12169f2a6ce848f1a73e1e544788310"

        def install
          bin.install "koctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.6.0/konnect-orchestrator_linux_arm64.zip"
        sha256 "d62309750a83cc63cc912abf24859270b75fdea953327eeb7a1ea80012a4af03"

        def install
          bin.install "koctl"
        end
      end
    end
  end

  test do
    system "#{bin}/koctl", "version"
  end
end
