# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KonnectOrchestrator < Formula
  desc "Konnect Organization orchestration via declarative configuration"
  homepage "https://github.com/kong/konnect-orchestrator"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.1.0/konnect-orchestrator_darwin_amd64.zip"
      sha256 "c3df0d457740830b73012fee945c1dc9255bb8d4388856b30edeb5d0fd5d4a45"

      def install
        bin.install "koctl"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.1.0/konnect-orchestrator_darwin_arm64.zip"
      sha256 "e762198cffd72f8bcbefcd5b36a9ee36c288bf9fe2235ef5178aa48c8706f081"

      def install
        bin.install "koctl"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.1.0/konnect-orchestrator_linux_amd64.zip"
        sha256 "3fc7e1fbf9a246287bff72a904a00e18a5f1fc4c543767d492a84e6f0dd2a5ab"

        def install
          bin.install "koctl"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kong/konnect-orchestrator/releases/download/v0.1.0/konnect-orchestrator_linux_arm64.zip"
        sha256 "e873311af08c72282bb3d2d99d8da146622df3fcdf4d72bab348f484f02dafc5"

        def install
          bin.install "koctl"
        end
      end
    end
  end

  test do
    system "#{bin}/koctl", "version"
  end
end
